[package]
name = "stors"
version = "0.1.1"
authors = ["George Rogers <grogers385@gmail.com>"]

[dependencies]
glob = "*"
iron = "*"
router = "*"
staticfile = "*"
handlebars-iron = "*"
rustc-serialize = "*"
